# Generated by Django 4.1.5 on 2023-01-16 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_rename_message_post_post_alter_post_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="post",
            new_name="message",
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("user", "message")},
        ),
    ]
